---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-schema-creator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-schema-creator-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: database-schema-creator
  namespace: default
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-database-schema
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: database-schema-creator
      containers:
      - name: schema-creator
        image: ghcr.io/colinjlacy/knapscen-create-database:latest
        env:
        - name: MYSQL_HOST
          value: "my-test-cluster.default.svc.cluster.local"
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: my-test-cluster-privsecrets
              key: clusterAdminUsername
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-test-cluster-privsecrets
              key: clusterAdminPassword
        - name: SCHEMA_NAME
          value: "bassline_boogie"
        - name: DB_USER
          value: "bassline_boogie_user"
        - name: K8S_NAMESPACE
          value: "default"
        - name: SECRET_NAME
          value: "bassline_boogie_credentials"
        - name: MYSQL_PORT
          value: "3306"
      restartPolicy: OnFailure

